import { getDatabaseSpreadsheetId, getSheetsClient } from "@/lib/googleSheets";
import type { CreatePaymentTermPayload, PaymentTerm, UpdatePaymentTermPayload } from "@/types/paymentTerm";

const SHEET = "PaymentTerms";
const RANGE = `${SHEET}!A2:M`;
const integer = (value: unknown, name: string, optional = false): number | undefined => { if (value === "" || value === undefined || value === null) return optional ? undefined : 0; const number = Number(value); if (!Number.isInteger(number) || number < 0) throw new Error(`${name} must be a non-negative whole number.`); return number; };
const percent = (value: unknown): number | undefined => { if (value === "" || value === undefined || value === null) return undefined; const number = Number(value); if (!Number.isFinite(number) || number < 0 || number > 100) throw new Error("Down payment percent must be between 0 and 100."); return number; };
function fromRow(row: unknown[]): PaymentTerm { return { paymentTermId: String(row[0] ?? ""), code: String(row[1] ?? ""), name: String(row[2] ?? ""), description: String(row[3] ?? ""), dueDays: row[4] === "" || row[4] === undefined ? undefined : Number(row[4]), downPaymentPercent: row[5] === "" || row[5] === undefined ? undefined : Number(row[5]), balanceTerms: String(row[6] ?? ""), status: String(row[7] ?? "Active") === "Inactive" ? "Inactive" : "Active", sortOrder: Number(row[8]) || 0, createdBy: String(row[9] ?? ""), createdAt: String(row[10] ?? ""), updatedBy: String(row[11] ?? ""), updatedAt: String(row[12] ?? "") }; }
function validate(payload: CreatePaymentTermPayload, existing: PaymentTerm[], exclude?: string) { const code = payload.code.trim(); const name = payload.name.trim(); if (!code || !name) throw new Error("Code and name are required."); if (existing.some((term) => term.paymentTermId !== exclude && term.code.trim().toLowerCase() === code.toLowerCase())) { const error = new Error("Payment term code already exists."); error.name = "ConflictError"; throw error; } if (existing.some((term) => term.paymentTermId !== exclude && term.name.trim().toLowerCase() === name.toLowerCase())) { const error = new Error("Payment term name already exists."); error.name = "ConflictError"; throw error; } integer(payload.dueDays, "Due days", true); percent(payload.downPaymentPercent); integer(payload.sortOrder, "Sort order"); }
function row(term: PaymentTerm) { return [term.paymentTermId, term.code, term.name, term.description, term.dueDays ?? "", term.downPaymentPercent ?? "", term.balanceTerms, term.status, term.sortOrder, term.createdBy, term.createdAt, term.updatedBy, term.updatedAt]; }
export async function getPaymentTerms(): Promise<PaymentTerm[]> { const sheets = await getSheetsClient(); const spreadsheetId = await getDatabaseSpreadsheetId(); const result = await sheets.spreadsheets.values.get({ spreadsheetId, range: RANGE }); return (result.data.values ?? []).map(fromRow).filter((term) => term.paymentTermId).sort((a,b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name)); }
export async function addPaymentTerm(payload: CreatePaymentTermPayload, actor: string): Promise<PaymentTerm> { const existing = await getPaymentTerms(); validate(payload, existing); const highest = existing.reduce((max, term) => Math.max(max, Number(/^PT-(\d+)$/.exec(term.paymentTermId)?.[1]) || 0), 0); const now = new Date().toISOString(); const term: PaymentTerm = { ...payload, code: payload.code.trim(), name: payload.name.trim(), description: payload.description?.trim() ?? "", balanceTerms: payload.balanceTerms?.trim() ?? "", dueDays: integer(payload.dueDays, "Due days", true), downPaymentPercent: percent(payload.downPaymentPercent), sortOrder: integer(payload.sortOrder, "Sort order") ?? 0, status: payload.status ?? "Active", paymentTermId: `PT-${String(highest + 1).padStart(3, "0")}`, createdBy: actor, createdAt: now, updatedBy: actor, updatedAt: now }; const sheets = await getSheetsClient(); const spreadsheetId = await getDatabaseSpreadsheetId(); await sheets.spreadsheets.values.append({ spreadsheetId, range: RANGE, valueInputOption: "USER_ENTERED", requestBody: { values: [row(term)] } }); return term; }
export async function updatePaymentTerm(payload: UpdatePaymentTermPayload, actor: string): Promise<PaymentTerm> { const sheets = await getSheetsClient(); const spreadsheetId = await getDatabaseSpreadsheetId(); const raw = await sheets.spreadsheets.values.get({ spreadsheetId, range: RANGE }); const index = (raw.data.values ?? []).findIndex((entry) => String(entry[0] ?? "") === payload.paymentTermId); if (index < 0) throw new Error("Payment term not found."); const existing = (raw.data.values ?? []).map(fromRow).filter((term) => term.paymentTermId); const current = existing.find((term) => term.paymentTermId === payload.paymentTermId)!; const next: PaymentTerm = { ...current, ...payload, code: payload.code?.trim() ?? current.code, name: payload.name?.trim() ?? current.name, description: payload.description?.trim() ?? current.description, balanceTerms: payload.balanceTerms?.trim() ?? current.balanceTerms, status: payload.status ?? current.status, updatedBy: actor, updatedAt: new Date().toISOString() }; validate(next, existing, next.paymentTermId); next.dueDays = integer(next.dueDays, "Due days", true); next.downPaymentPercent = percent(next.downPaymentPercent); next.sortOrder = integer(next.sortOrder, "Sort order") ?? 0; await sheets.spreadsheets.values.update({ spreadsheetId, range: `${SHEET}!A${index + 2}:M${index + 2}`, valueInputOption: "USER_ENTERED", requestBody: { values: [row(next)] } }); return next; }
