import { getDatabaseSpreadsheetId, getSheetsClient } from "@/lib/googleSheets";
import type { CreateWarehousePayload, Warehouse } from "@/types/warehouse";

const SHEET = "Warehouses";
const RANGE = `${SHEET}!A2:M`;
const rowNumber = (id: string) => Number(id.replace("warehouse_", ""));
const toBool = (value: unknown) => ["true", "yes", "1", "active"].includes(String(value ?? "").trim().toLowerCase());
const mapRow = (row: string[], index: number): Warehouse => ({ id: `warehouse_${index + 2}`, warehouseId: String(row[0] ?? "").trim(), companyId: String(row[1] ?? "").trim(), code: String(row[2] ?? "").trim(), name: String(row[3] ?? "").trim(), addressLines: String(row[4] ?? "").trim(), cityProvincePostal: String(row[5] ?? "").trim(), contactPersonPhone: String(row[6] ?? "").trim(), active: toBool(row[7]), sortOrder: Number(row[8]) || 0, createdBy: String(row[9] ?? "").trim() || undefined, createdAt: String(row[10] ?? "").trim() || undefined, updatedBy: String(row[11] ?? "").trim() || undefined, updatedAt: String(row[12] ?? "").trim() || undefined });
async function readRows() { const sheets = await getSheetsClient(); const spreadsheetId = await getDatabaseSpreadsheetId(); const response = await sheets.spreadsheets.values.get({ spreadsheetId, range: RANGE }); return { sheets, spreadsheetId, values: response.data.values ?? [] }; }
export async function getWarehouses() { const current = await readRows(); return current.values.map(mapRow).filter(row => row.name).sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name)); }
export async function addWarehouse(payload: CreateWarehousePayload): Promise<Warehouse> { const current = await readRows(); const max = current.values.reduce((n, row) => Math.max(n, Number(String(row[0] ?? "").match(/\d+/)?.[0] ?? 0)), 0); const id = payload.warehouseId.trim() || `WH-${max + 1}`; const now = new Date().toISOString(); const values = [[id, payload.companyId.trim(), payload.code.trim(), payload.name.trim(), payload.addressLines.trim(), payload.cityProvincePostal.trim(), payload.contactPersonPhone.trim(), payload.active ? "TRUE" : "FALSE", String(payload.sortOrder || 0), payload.createdBy?.trim() ?? "", now, payload.updatedBy?.trim() ?? "", now]]; await current.sheets.spreadsheets.values.append({ spreadsheetId: current.spreadsheetId, range: `${SHEET}!A:M`, valueInputOption: "USER_ENTERED", requestBody: { values } }); return mapRow(values[0], current.values.length); }
export async function updateWarehouse(id: string, payload: CreateWarehousePayload) { const current = await readRows(); const index = rowNumber(id); const old = current.values[index - 2] ?? []; const now = new Date().toISOString(); const values = [[payload.warehouseId.trim() || old[0] || "", payload.companyId.trim(), payload.code.trim(), payload.name.trim(), payload.addressLines.trim(), payload.cityProvincePostal.trim(), payload.contactPersonPhone.trim(), payload.active ? "TRUE" : "FALSE", String(payload.sortOrder || 0), old[9] || "", old[10] || now, payload.updatedBy?.trim() || old[11] || "", now]]; await current.sheets.spreadsheets.values.update({ spreadsheetId: current.spreadsheetId, range: `${SHEET}!A${index}:M${index}`, valueInputOption: "USER_ENTERED", requestBody: { values } }); return mapRow(values[0], index - 2); }
export async function deleteWarehouse(id: string) { const { sheets, spreadsheetId } = await readRows(); const meta = await sheets.spreadsheets.get({ spreadsheetId, ranges: [SHEET], fields: "sheets.properties(sheetId,title)" }); const sheetId = meta.data.sheets?.find(s => s.properties?.title === SHEET)?.properties?.sheetId; if (sheetId === undefined) throw new Error(`Sheet "${SHEET}" not found.`); const index = rowNumber(id) - 1; await sheets.spreadsheets.batchUpdate({ spreadsheetId, requestBody: { requests: [{ deleteDimension: { range: { sheetId, dimension: "ROWS", startIndex: index, endIndex: index + 1 } } }] } }); }
