const fs = require('fs');
let p, c, old, newText;

// Fix ftiSheets.ts - replace the corrupted withdrawFTIRequest function
p = 'src/lib/ftiSheets.ts';
c = fs.readFileSync(p, 'utf8');

old = 'export async function withdrawFTIRequest(\n  controlNo: string,\n  userId: string,\n  force: boolean = false,\n): Promise<void> {\n  const spreadsheetId = await getDatabaseSpreadsheetId();\n  const all = await getAllFTIRequests();\n  const idx = all.findIndex((r) => r.controlNo === controlNo);\n  if (idx === -1) throw new Error(FTI request  not found);\n  const request = all[idx];\n  const status = (request.status || \'\').toUpperCase();\n  if (status !== \'SENT\') {\n    throw new Error(Cannot withdraw request : status is \"\". Only SENT requests can be withdrawn.);\n  }\n  if (!force && request.approvedByUserId) {\n    throw new Error(Cannot withdraw request : an approver has already been assigned. Contact an administrator.);\n  }\n  if (!force && request.userId !== userId) {\n    throw new Error(You can only withdraw your own requests.);\n  }\n  const rowNumber = idx + 2;\n  const sheets = await getSheetsClient();\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!C\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'DRAFT\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!G\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!H\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!I\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!J\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!K\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  invalidateFTICache();\n}\n\nexport async function deleteFTIRequest(controlNo: string): Promise<void> {';

newText = 'export async function withdrawFTIRequest(\n  controlNo: string,\n  userId: string,\n  force: boolean = false,\n): Promise<void> {\n  const spreadsheetId = await getDatabaseSpreadsheetId();\n  const all = await getAllFTIRequests();\n  const idx = all.findIndex((r) => r.controlNo === controlNo);\n  if (idx === -1) throw new Error(\FTI request \ not found\);\n  const request = all[idx];\n  const status = (request.status || \'\').toUpperCase();\n  if (status !== \'SENT\') {\n    throw new Error(\Cannot withdraw request \: status is "\". Only SENT requests can be withdrawn.\);\n  }\n  if (!force && request.approvedByUserId) {\n    throw new Error(\Cannot withdraw request \: an approver has already been assigned. Contact an administrator.\);\n  }\n  if (!force && request.userId !== userId) {\n    throw new Error(\'You can only withdraw your own requests.\');\n  }\n  const rowNumber = idx + 2;\n  const sheets = await getSheetsClient();\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!C\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'DRAFT\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!G\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!H\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!I\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!J\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  await sheets.spreadsheets.values.update({\n    spreadsheetId,\n    range: \\!K\\,\n    valueInputOption: \'USER_ENTERED\',\n    requestBody: { values: [[\'\']] },\n  });\n  invalidateFTICache();\n}\n\nexport async function deleteFTIRequest(controlNo: string): Promise<void> {';

c = c.replace(old, newText);
fs.writeFileSync(p, c);
console.log('OK: ftiSheets.ts fixed');

console.log('Done');
